---
- name:  Enter the matrix to get hostname
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: add host to local inventory
      add_host: 
        groups: VDI_STD_Master_Local
        name: "{{ HostNameFact }}"

- name: VDI AZPJP
  hosts: VDI_STD_Master_Local
  vars:
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_read_timeout_sec: 900
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: credssp
    reboot_timeout: 1800
    CoreApp_Source: \\AALWSUSGP201.wwg00m.rootdom.net\packages

  gather_facts: false
  tasks:

    - name: Wait for WinRM 
      wait_for_connection:
        delay: 10
        timeout: 3000

################################################################ System Local ####################################################

    - name:  Set System Local for Japan
      win_dsc:
        resource_name: SystemLocale
        SystemLocale: 'ja-JP'
        IsSingleInstance: 'Yes'
      register: SystemLocaleSet

    - name:  Reboot After Local Change 
      win_reboot:
        post_reboot_delay: 120
        reboot_timeout: 1800
      when: SystemLocaleSet.changed
    
    - name: Run Maintenance Defender Task 
      win_shell: Start-ScheduledTask -TaskName "\Microsoft\Windows\Windows Defender\Windows Defender Cache Maintenance"

################################################################## APPS #########################################################

