---
- name: Enter the matrix to get hostname.
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: add host to local inventory
      add_host:
        groups: VDI_STD_Master_Local
        name: "{{ HostNameFact }}"  

- name: VDI AGCS
  hosts: VDI_STD_Master_Local
  vars:
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_read_timeout_sec: 900
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: credssp
    reboot_timeout: 1800
    CoreApp_Source: \\AALWSUSGP201.wwg00m.rootdom.net\packages
  
  gather_facts: false
  tasks: 
    
    - name: Wait for Winrm 
      wait_for_connection:
        delay: 10
        timeout: 3000

    - name: Install SSCM Agent; AppId - 
      win_dsc: 
        resource_name: Package
        Ensure: 'Present'
        path: '\\aalmpssgp201\sources\Packages\DXC\SCCM Agent\5.00.9096.1024\ccmsetup.exe'
        Name: 'Configuration Manager Client'
        ProductId: '{9EE3DE97-08FA-4134-837A-F1FACC7BEFDD}'  # version 5.00.9096.1024
        Arguments: '/mp:AALMPSSGP201.wwg00m.rootdom.net SMSMP=AALMPSSGP201.wwg00m.rootdom.net SMSSITECODE=AP1'
      ignore_errors: true
      # register: SCCMInstalled

    - pause: 
        minutes: 15

    - name: RunMachine policy retrival and Application Deployment Cycle ; AppId -       
      win_shell: ([wmiClasss] "root\ccm:SMS_Client").TriggerSchedule('{00000000-0000-0000-0000-000000000021}') # Machine policy retrival $ evaluation cycle 
      ignore_erros: true

############################################## System Locale #########################################      
    - name: Set System Loacale for Korea
      win_dsc: 
        resource_name: SystemLocale
        SystemLocale: 'ko-KR'
        InSingleInstance: 'Yes'
      register: SystemLocaleSet
      when: OE == "AGCSKR"  
      
    - name: Set System Loacale for Korea
      win_dsc: 
        resource_name: SystemLocale
        SystemLocale: 'ja-JP'
        InSingleInstance: 'Yes'
      register: SystemLocaleSet
      when: OE == "AGCSJP"

    - name: Reboot after Locale change
      win_reboot: 
        post_reboot_delay: 120
        reboot_timeout: 1800
      when: SystemLocaleSet.changed

    - name: run maintance defender task 
      win_shell: Start-ScheduledTask -TaskName "\Microsoft\Windows\Windows Defender\Windows Defender Cache Maintenance"

################################################### APPS ######################################################

    - name: XPS Viewer install - 5657;
      win_dsc: 
        resource_name: InstallerClass
        PackageName: 'XPS Viewer'
        Ensure: 'Present'
        Executable: 'Installer_XPS-ansible.ps1'
        Source: '\\aalmpssgp201\sources\Packages\DXC\XPS\' 
        DetectionFilePath: 'C:\Windows\installer\XPSViewer_Success.txt'
        Timeout: 1800

    # - name: Citrix_Virtual_Desktop_Agent_Workstation_OS_1912.4000; AppId - 8021;
    #   win-Dsc: 
    #     resource_name: InstallerClass
    #     PackageName: 'VDAWorkstation'
    #     Ensure: 'Present'
    #     Executable: 'VDAWorkstationSetup_1912_4000.cmd'
    #     Source: '{{ CoreApp_Source }}\Citrix\Virtual_Desktop_Agent\VDA_1912_CU4\Workstation\'
    #     DetectionFilePath: 'C:\Program Files\Citrix\Virtual Desktop Agent\BrokerAgent.exe'

    - name: fineprint_PDF-Factory-Pro_4.81; AppId - 1179
      win_dsc: 
        resource_name: InstallerClass
        PackageName: 'pdfFactory Pro'
        Ensure: 'Present'
        Executable: 'Install.cmd'
        Source: '{{ CoreApp_Source }}\Fineprint\PDF_Factory_Pro\4.81\'
        #DetectionProductRegistryKeys: 'HKLM:\SOFTWARE\DXC\Packages\5859_FinePrintSoftware_pdfFactory_7.34_XEN_R1'
        DetectionFilePath:
          - "C:\Programme\Allianz\\PDF-Factory\\fpp450-dt.chm"
          - "C:\Programme\Allianz\\PDF-Factory\\fpp450en.chm"

    - name: IBMi Access Client ODBC 1.1.8.1 Drivers Only - APAC; AppId - 7732
      win_dsc: 
        resource_name: InstallerClass
        PackageName: 'IBMi Access Client ODBC 1.1.8.1'
        Ensure: 'Present'
        Executable: 'Install.bat'
        Source: '\\aalmpssgp201\sources\Packages\AGCS\IBMiAccessClientSolutions\'
        DetectionProductUnistallRegKeyValue: '{E32ABB01-6901-4060-A9BA-D58CC24ABD1A}'

    # - name: ODBC_Driver_for_SQL_server_v2012; AppId - 8279;
    #   win_dsc:
    #     resource_name: InstallerClass
    #     PackageName: 'ODBC_Driver_for_SQL_server_v2012'
    #     Ensure: 'Present'
    #     Executable: 'Install.bat'
    #     Source: '\\aalmpssgp201\sources\Packages\DXC APAC\Microsoft\8279_ODBC_Driver_for_SQL_Server-v2012\13\'
    #     DetectionProductUnistallRegKeyValue: '{2D98CD18-5754-4D94-B7E8-E6E11DAA56B1}'

    - name: 505_AGCSKR_KoreanFonts_1.0_R1; AppId - 505
      win_dsc: 
        resource_name: InstallerClass
        PackageName: 'KoreanFonts_1.0_R1'
        Ensure: 'Present'
        Executable: 'Install.vbs'
        Source: '\\aalmpssgp201\sources\Packages\AGCS\505_AGCSKR_KoreanFonts_1.0_R1\'
        DetectionProductUnistallRegKeyValue: '{B05E117E-6143-4935-A8C9-7612B975B8A8}'

    # - name: 486_AGCSKR_Hangul12020_11.0.0.1_R2; AppId - 486
    #   win_dsc:
    #     resource_name: InstallerClass
    #     PackageName: 'Hangul12020_11.0.0.1_R2'
    #     Ensure: 'Present'
    #     Executable: 'Install.vbs'
    #     Source: '\\aalmpssgp201\sources\Packages\AGCS\486_AGCSKR_Hangul12020_11.0.0.1_R2\'
    #     DetectionProductUnistallRegKeyValue: '{F74FE1CA-CA34-4B75-95E9-00FA0F85B8F6}'

    # - name: Oracle_12C_Admin_Client_32-bit-12.1.0.2_R1; AppId - 5199
    #   win_dsc: 
    #     resource_name: InstallerClass
    #     PackageName: 'Oracle_12C_Admin_Client_32-bit-12.1.0.2_R1'
    #     Ensure: 'Present'
    #     Executable: 'Install.vbs'
    #     Source: '{{ CoreApp_Source }}\Oracle\12C_Admin_Client_32_bit\12.1.0.2_R1\'
    #     DetectionFilePath: 'C:\Oracle\32bit\product\12.1.0.2\client_12c\BIN\orabase.exe'
    #     TimeOut: 600
    #   ignore_errors: true

    # - name: Oracle_12C_Admin_Client_64-bit-12.1.0.2_R1; AppId - 4359
    #   win_dsc: 
    #     resource_name: InstallerClass
    #     PackageName: 'Oracle_12C_Admin_Client_x64'
    #     Ensure: 'Present'
    #     Executable: 'Install.bat'
    #     Source: '{{ CoreApp_Source }}\Oracle\12C_Admin_Client_64_bit\12.1.0.2\'
    #     DetectionFilePath: 'C:\oracle\64bit\product\12.1.0.2\client_12c\BIN\orabase.exe'
    #     TimeOut: 600
    #   ignore_errors: true

    - name: Create_Oracle_Folder
      win_dsc: 
        resource_name: File
        Type: 'Directory'
        DestinationPath: 'C:\oracle'
        Ensure: 'Present'

    - name:  Oracle_Permission
      win_acl:
        path: 'C:\oracle'
        user: 'Authenticated Users'
        rights: Read,Write
        type: allow
        state: present 
        inherit: ContainerInherit, ObjectInherit
        propagaton: 'None'

    - name: remove_oracle_home
      win_dsc:
        resource_name: Environment
        Ensure: 'Absent'
        Name: 'Oracle_home'

    # - name: Oracle_Instant_Client_19.3x64; AppId - 4705
    #   win_dsc:
    #     resource_name: InstallerClass
    #     PackageName: 'Oracle_Instant_Client_19.3x64_4705'
    #     Ensure: 'Present'
    #     Executable: 'Install.cmd'
    #     Source: '{{ CoreApp_Source }}\Oracle\Instant_Client_19.3_x64\'
    #     DetectionProductionUninstallRegKeyValue: '{65222AB8-5566-4717-B46D-817C9BDB34D3}'

    # - name: Installer_Go_To_assit; AppId - 3651
    #   win_dsc:
    #     resource_name: InstallerClass
    #     PackageName: 'Citrix_Goto_Assit_Customer_11_9_0_1280_3651'
    #     Ensure: 'Present'
    #     Executable: 'Install.vbs'
    #     Source: '{{ CoreApp_Source }}\Citrix\Goto_Assit_Customer\11.9.0.1280_3651\'
    #     DetectionProductRegistryKeys: 'HKLM:SOFTWARE\Wow6432Node\CSC\Packages\3651_Citrix_CitrixGoToAssitCorporate_11.9_PKG_R1'
    #     DetectionProductUninstallRegistryKeys: '{95237e14-3f0a-410b-9378-b3303003fc6c}'

    - name: Install_Printer_Drivers; AppId - App_Printer_Drivers
      win_dsc:
        resource_name: InstallerClass
        PackageName: 'Printer_drivers'
        Ensure: 'Present'
        Executable: 'Install.cmd'
        Source: '\\aalmpssgp201\sources\Packages\Print_Drivers\all_os\Printer Driver Installation 2.0\'
        DetectionFilePath: 'C:\Windows\Installer\printers_add.log'

    - name: KonicaMinolta_FaxDriver_5.4.0.0; AppId - 
      win_dsc:
        resource_name: InstallerClass
        PackageName: 'KonicaMinolta_FaxDriver_5.4.0.0'
        Ensure: 'Present'
        Executable: 'Install.bat'
        Source: '\\aalmpssgp201\sources\Packages\AGCS\OS and INFRA\KonicaMinolta_FaxDriver_5.4.0.0\'

    - name:  Install_TortoiseSVN_Tortoise_1.13.2; AppId - 5049
      win_dsc:
        resource_name: InstallerClass
        PackageName: 'TortoiseSVN_Tortoise_1.13.2'
        Ensure: 'Present'
        Executable: 'Install.bat'
        Source: '\\aalmpssgp201\sources\Packages\TortoiseGit\5049_TortoiseSVN_1.13.2_R1\'
        DetectionProductUnistallRegKeyValue: '{F7080EF1-BD21-483B-ACAE-E19FAA2DF458}'

    - name:  Install_MS_VSTOR_2010; AppId - 3694
      win_dsc: 
        resource_name: InstallerClass
        PackageName: 'MS_VSTOR2010_10.0.60724x64'
        Ensure: 'Present'
        Executable: 'Install.vbs'
        Source: '{{ CoreApp_Source }}\Microsoft\Visual_Studio_2010_Tools_for_Office_Runtime\10.0.60724_x64\' 
        DetectionProductRegistryKeys: 'HKLM:\SOFTWARE\Microsoft\Visual_Studio_2010_Tools_for_Office_Runtime\10.0.60724_x64'

    - name:  HP Appl Lifecycle MGMT; AppId - 3694
      win_dsc:
        resource_name: InstallerClass
        PackageName: 'HP_(3479)_Application_Lifecycle_Management\12.55\' 
        Ensure: 'Present'
        Executable: 'Install.vbs'
        Source: '{{ CoreApp_Source }}\HP\(3479)_Application_Lifecycle_Management\12.55\'
        DetectionProductUnistallRegKeyValue: '{B030EFD4-65C7-47AC-B8A0-726613AEB460}'

    - name:  Reboot Action for VS2010 Shell Package [SHELL]
      win_reboot: 
        post_reboot_delay: 120
        reboot_timeout: 1800

    - name:  Microsoft_Visual_Studio_2010_Shell_2010_SP1; AppId - 1748
      win_dsc:
        resource_name: InstallerClass
        PackageName: 'Microsoft_Visual_Studio_2010_Shell_2010_SP1'
        Ensure: 'Present'
        Executable: 'Install.vbs'
        Source: '{{ CoreApp_Source }}\Microsoft\Visual_Studio_2010_Shell\2010_SP1\'
        DetectionProductUnistallRegKeyValue: '{D64B6984-242F-32BC-B008-752806E5FC44}'

        
          


      

    









          



        